CREATE TABLE cities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    boundary geometry(Polygon, 4326) NOT NULL,
    CONSTRAINT uq_cities_name UNIQUE (name)
);

CREATE TABLE neighborhoods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    boundary geometry(Polygon, 4326) NOT NULL,
    CONSTRAINT uq_neighborhoods_city_name UNIQUE (city_id, name),
    CONSTRAINT fk_neighborhoods_city_id
        FOREIGN KEY (city_id)
        REFERENCES cities (id)
        ON DELETE CASCADE
);