CREATE TABLE listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    neighborhood_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    status VARCHAR(50) NOT NULL,
    purpose VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    price NUMERIC(14, 2) NOT NULL,
    area_sqm NUMERIC(14, 2) NOT NULL,
    bedrooms INTEGER NOT NULL DEFAULT 0,
    location geometry(Point, 4326) NOT NULL,
    price_per_sqm NUMERIC(14, 2) GENERATED ALWAYS AS (price / NULLIF(area_sqm, 0)) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_listings_owner_id
        FOREIGN KEY (owner_id)
        REFERENCES users (id),
    CONSTRAINT fk_listings_neighborhood_id
        FOREIGN KEY (neighborhood_id)
        REFERENCES neighborhoods (id)
);