CREATE TABLE listing_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    s3_key VARCHAR(512) NOT NULL,
    thumbnail_key VARCHAR(512),
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_listing_images_listing_display_order UNIQUE (listing_id, display_order),
    CONSTRAINT fk_listing_images_listing_id
        FOREIGN KEY (listing_id)
        REFERENCES listings (id)
        ON DELETE CASCADE
);