CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    price NUMERIC(14, 2) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_price_history_listing_id
        FOREIGN KEY (listing_id)
        REFERENCES listings (id)
        ON DELETE CASCADE
);