spring:
  application:
    name: aqar

  datasource:
    url: jdbc:postgresql://localhost:5432/aqar
    username: aqar
    password: aqar

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  dropbox:
    access-token: sl.dummy_token_for_local_dev
  security:
    jwt:
      issuer: aqar
      secret: change-this-development-secret-to-a-long-random-value-change-this-development-secret
      access-token-ttl: 15m
    refresh-token:
      ttl: 7d

server:
  port: 8080
